version: '3.7'
services:
   #   zookeeper:
   #     image: wurstmeister/zookeeper
   #     container_name: zookeeper
   #     expose:
   #       - "2181"
   #     ports:
   #       - 2181:2181

   #   kafka:
   #     image: wurstmeister/kafka
   #     container_name: kafka
   #     expose:
   #       - "9092"
   #     ports:
   #       - 9092:9092
   #     environment:
   #       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   #       KAFKA_ADVERTISED_PORT: 9092
   #       KAFKA_ADVERTISED_HOST_NAME: kafka
   #       KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:19092
   #       KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://0.0.0.0:19092
   #       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
   #       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

   pyspark:
      image: jupyter/pyspark-notebook
      container_name: pyspark-notebook-twitter
      ports:
         - '8888:8888'
      #     depends_on:
      #       - "kafka"
      #     links:
      #       - kafka
      volumes:
         - ./spark-lab/:/home/jovyan/work/
#   kafka_manager:
#     image: hlebalbau/kafka-manager:1.3.3.18
#     container_name: kafka_manager
#     expose:
#       - "9000"
#     ports:
#       - 9000:9000
#     environment:
#       ZK_HOSTS: "zookeeper:2181"
#       APPLICATION_SECRET: "random-secret"
#       command: -Dpidfile.path=/dev/null
#     links:
#         - kafka
#         - zookeeper
#     depends_on:
#         - "zookeeper"
#         - "kafka"
