
version: '3'

services:
  twitter:
    container_name: twitter
    build: 
      context: .
      dockerfile: ./docker/twitter/Dockerfile
    volumes:
      - .:/code
    ports:
      - "5001:5001"
      
  spark-master:
    container_name: spark-master
    build: 
      context: .
      dockerfile: ./docker/spark-master/Dockerfile
    ports:
      - "7077:7077"
      - "8080:8080"
      - "6066:6066" 
    volumes:
      - .:/code

  spark-worker:
    container_name: spark-worker
    build: 
      context: .
      dockerfile: ./docker/spark-worker/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/code
    depends_on:
      - spark-master

  spark-submit:
    container_name: spark-submit
    build: 
      context: .
      dockerfile: ./docker/spark-submit/Dockerfile
    volumes:
      - .:/code
    environment:
      - TWITTER_APP_IP=twitter
    depends_on:
      - spark-master
      - spark-worker

  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "9090:9090"
    # network_mode: "host"
    volumes:
      - .:/code
    depends_on:
      - spark-master
      - spark-submit
      - spark-worker
      - twitter
